id: node.event.default
uuid: 300fd96e-afed-41cd-8f06-0680e5362d53
targetEntityType: node
bundle: event
mode: default
content:
  body:
    type: text_default
    weight: 0
    settings: {  }
    label: above
  field_date:
    type: datetime_plain
    weight: 1
    settings: {  }
    label: above
  field_venue:
    type: entity_reference_label
    weight: 2
    settings:
      link: true
    label: above
hidden:
  langcode: true
status: true
