id: node.field_date
uuid: 4c4c9098-cb7d-420e-bf00-fe96219fc764
status: true
langcode: en
name: field_date
entity_type: node
type: datetime
settings:
  datetime_type: datetime
module: datetime
locked: false
cardinality: '1'
translatable: false
indexes: {  }
