id: node.field_event
uuid: d47ce144-2636-4c63-bc00-f82e0b74a7ef
status: true
langcode: en
name: field_event
entity_type: node
type: entity_reference
settings:
  target_type: node
module: entity_reference
locked: false
cardinality: '1'
translatable: false
indexes: {  }
