id: node.event.body
uuid: 67d2c7bf-6363-438a-b700-e66f4e3ae1e0
status: true
langcode: en
field_name: body
entity_type: node
bundle: event
label: Description
description: ''
required: 0
default_value: {  }
default_value_function: ''
settings:
  text_processing: '1'
  display_summary: 1
field_type: text_with_summary
